// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * `prisma generate` runs in postinstall on Vercel before env vars (e.g. DATABASE_URL)
 * are always available. A placeholder is fine — generate does not open a DB connection.
 * Real commands (migrate, studio, seed) require DATABASE_URL in .env or the host.
 */
const databaseUrl =
  process.env.DATABASE_URL ??
  "postgresql://prisma_generate_placeholder:unused@127.0.0.1:5432/prisma_generate_only";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
